version: '3.0.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "cryptonary"
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"