[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Joachim Hodana", email = "stylek777@gmail.com"},
]
dependencies = [
    "flask>=3.0.0",
    "psycopg-binary>=3.1.14",
    "sqlalchemy>=2.0.23",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

